### ISSUE TITLE
Не собирается проект

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#11]
Сейчас не собирается проект, появляются такие ошибки:

![Снимок экрана в 2019-11-06 18-26-24](https://user-images.githubusercontent.com/38564412/68311740-0a522600-00c3-11ea-8fa1-fe2a0271fcd9.png)

**Comment by imin314** [comment]
Проблема была с именами шрифтов - пути на Windows нечувствительны к регистру, поэтому ошибки не возникало. Сейчас должен собираться.
