### ISSUE TITLE
Баги слайдера

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#12]
Почему-то слайдер можно перетаскивать не только кликом на thumb, но и кликом на track в совершенно другом месте:

![Peek 2019-11-06 18-30](https://user-images.githubusercontent.com/38564412/68312110-a0864c00-00c3-11ea-93db-d3d32178963b.gif)

**Comment by MorganaLF** [comment]
Бегунок не всегда останавливается там, где остановилось движение мыши, иногда слегка "перескакивает"

![Peek 2019-11-06 18-33](https://user-images.githubusercontent.com/38564412/68312348-fa871180-00c3-11ea-9d8d-d85fa03d86a7.gif)

**Comment by MorganaLF** [comment]
Валидация немного некорректно работает, я ввела невалидное значение в `min`, а в тексте ошибки: `Incorrect value for step option`

![Снимок экрана в 2019-11-06 18-35-28](https://user-images.githubusercontent.com/38564412/68312592-581b5e00-00c4-11ea-80ac-f3407c7a1917.png)

**Comment by imin314** [comment]
Поправила баги с валидацией и с перетаскиванием бегунка.
Когда проверяла, вылезли ошибки, которых раньше не видела, долго разбиралась с ними.

**Comment by MorganaLF** [comment]
Теперь появился баг с передвижением по шагам: если стоит в настройках step = 1, бегунок передвигается на 2 деления

![Peek 2019-11-15 08-18](https://user-images.githubusercontent.com/38564412/68918745-94b01f00-0780-11ea-9451-294238ea720a.gif)

**Comment by MorganaLF** [comment]
При установлении отрицательного значения бегунок куда-то убежал)

![Снимок экрана в 2019-11-15 08-19-51](https://user-images.githubusercontent.com/38564412/68918820-cc1ecb80-0780-11ea-9deb-ff3726fca696.png)

**Comment by MorganaLF** [comment]
Если не заполнить поле grid, то шкала не отображается, так и должно быть?

![Снимок экрана в 2019-11-15 08-24-08](https://user-images.githubusercontent.com/38564412/68918960-4fd8b800-0781-11ea-8c0e-6207601c9368.png)

**Comment by MorganaLF** [comment]
Еще один момент со шкалой нужно будет поправить: сейчас у тебя можно поставить, например, `step: 9` и `interval: 10`, в итоге получается, что размер шага шкалы не обязательно кратный размеру шага слайдера. Думаю, лучше будет провалидировать значение `interval` у шкалы, чтобы пользователь не мог задавать абсолютно любое значение. 
Например, если у слайдера стоит размер шага 5, чтобы деления шкалы могли быть только на 5-10-15, либо на 10-20-30, либо на 25-50-75, и т. д., то есть всегда кратны 5.

![Снимок экрана от 2019-12-06 20-21-25](https://user-images.githubusercontent.com/38564412/70342421-03573880-1866-11ea-8923-2b32aeff9e98.png)

Точно так же с grid может странная ситуация получиться

![Снимок экрана от 2019-12-06 20-21-59](https://user-images.githubusercontent.com/38564412/70342465-1c5fe980-1866-11ea-92a0-fbe81517d503.png)

**Comment by imin314** [comment]
> Теперь появился баг с передвижением по шагам: если стоит в настройках step = 1, бегунок передвигается на 2 деления
> 

> При установлении отрицательного значения бегунок куда-то убежал)
> 

> Если не заполнить поле grid, то шкала не отображается, так и должно быть?
> 

> Еще один момент со шкалой нужно будет поправить: сейчас у тебя можно поставить, например, `step: 9` и `interval: 10`, в итоге получается, что размер шага шкалы не обязательно кратный размеру шага слайдера. Думаю, лучше будет провалидировать значение `interval` у шкалы, чтобы пользователь не мог задавать абсолютно любое значение.
> Например, если у слайдера стоит размер шага 5, чтобы деления шкалы могли быть только на 5-10-15, либо на 10-20-30, либо на 25-50-75, и т. д., то есть всегда кратны 5.
> 

Вроде все эти баги поправила.
