### ISSUE TITLE
MainView

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#13]
Сейчас не совсем понятно, для чего главная вьюха слушает события, которые именно ей никак не нужны, и почему она рассчитывает значения для других вьюх, например:

![Снимок экрана в 2019-11-15 08-56-04](https://user-images.githubusercontent.com/38564412/68920273-c972a500-0785-11ea-9c4e-a7beef50e5e7.png)

Учитывая то, что задача вью отрисовывать вид в соответствии с моделью, каждая отдельная вьюха это может делать самостоятельно, и производить для себя расчеты сама. А так у тебя они слишком зависят друг от друга сейчас.

**Comment by imin314** [comment]
У меня были сомнения по этому поводу с самого начала. Подумала, что раз вью главная, то она должна управлять остальными.
1) Сейчас контроллер связан только с главной вью и может подписать на события модели только методы главной вью.
2) События EventDispatcher второстепенные вью не выпускают.
2) Доступ к состоянию модели есть только у главной вью. Поэтому я некоторые расчеты производила в ней.
Наверное, я что-то неправильно поняла в плане самой MVC-архитектуры.

**Comment by MorganaLF** [comment]
> У меня были сомнения по этому поводу с самого начала. Подумала, что раз вью главная, то она должна управлять остальными.
> 
> 1. Сейчас контроллер связан только с главной вью и может подписать на события модели только методы главной вью.
> 2. События EventDispatcher второстепенные вью не выпускают.
> 3. Доступ к состоянию модели есть только у главной вью. Поэтому я некоторые расчеты производила в ней.
>    Наверное, я что-то неправильно поняла в плане самой MVC-архитектуры.

Ты можешь, например, генерировать события во вьюхах, которые являются частями главной вью, и в главной вью их слушать, а оттуда уже генерировать события для контроллера. 

Настройки и необходимые данные для составных вьюх можно спускать сверху, а расчеты уже делать непосредственно в них самих.

**Comment by imin314** [comment]
Поправила.
Главным изменением стало то, что ThumbView сам теперь слушает события мыши и вызывает соответствующие события EventDispatcher. Главная вьюха подписана на события EventDispatcher своих дочерних элементов.

**Comment by MorganaLF** [comment]
По идее, `minValue`, `maxValue` и т.д. может диспатчить только модель. Вью у тебя знает только про координаты своих элементов и максимум, что может посчитать из этих данных, это коэффициент.  Соответственно, и диспатчить из вьюхи ты можешь только те данные, которыми располагает вьюха. А `value` модель сама у себя должна посчитать.

![Снимок экрана от 2020-01-20 09-35-09](https://user-images.githubusercontent.com/38564412/72704065-af2fbb80-3b68-11ea-8b67-9d250d391512.png)

**Comment by MorganaLF** [comment]
Опечатка) Для того, чтобы замечать такие моменты, стоит поставить какое-нибудь расширение в IDE

![Снимок экрана от 2020-01-20 09-32-34](https://user-images.githubusercontent.com/38564412/72704112-d1c1d480-3b68-11ea-853c-34ea3d94b50e.png)

**Comment by imin314** [comment]
По этой ишью все поправила. Теперь модель и вью обмениваются между собой не значениями, а коэффициентами.
Спелчекер тоже поставила.
