### ISSUE TITLE
Model

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#14]
Для чего здесь нужны эти методы и зачем модели знать про ThumbDrag, ThumbMouseUp и т.п.? 

![Снимок экрана в 2019-11-15 09-01-28](https://user-images.githubusercontent.com/38564412/68920594-cb893380-0786-11ea-94e8-fc460c328387.png)

**Comment by MorganaLF** [comment]
Мне кажется, с индексами не очень удачное решение, нагляднее было бы, если бы это были соответствующие свойства с понятными именами

![Снимок экрана в 2019-11-15 09-04-43](https://user-images.githubusercontent.com/38564412/68920691-12772900-0787-11ea-8bb8-06f258318033.png)

**Comment by imin314** [comment]
> Для чего здесь нужны эти методы и зачем модели знать про ThumbDrag, ThumbMouseUp и т.п.?
Пользовательские колбэки тоже задаются через опции, которые получает модель.
Функции _makeOn..._ нужны, чтобы в контроллере назначить пользовательские функции слушателями соответствующих событий EventDispatcher.

**Comment by MorganaLF** [comment]
Все равно не совсем понятна мотивация. У тебя сейчас модель знает о структуре вью и о событиях вью, а по идее она о вью ничего не должна знать. Если, например, вместо mouseDown / mouseUp во вьюхе будет что-то другое, нужно будет менять модель, и это странно) Почему контроллер не может этим заниматься и сам общаться с вьюхами?

![Снимок экрана в 2019-11-15 11-43-34](https://user-images.githubusercontent.com/38564412/68929361-3e9da480-079d-11ea-985d-daa2056bcf2a.png)

И можешь привести пример, как это работает? Я пока что не поняла)

**Comment by imin314** [comment]
Я бы отнесла колбэки не к структуре вью, а к настройкам модели. То есть пользователь может в настройках, например, задать:
```
$('.slider').sliderPlugin({
  min: 0,
  max: 100,
  callbacks: {
    onThumbMouseDown: function() {
      alert('mouse down!');
    },
  },
});

Модель эту функцию записывает в makeOnThumbMouseDownCallback, а контроллер вызывает её при наступлении события thumbDownEvent, выпускаемого главным видом.

Если модель будет игнорировать эти пользовательские настройки колбэков, непонятно, каким образом, контроллер может узнать о них.

**Comment by imin314** [comment]
> Мне кажется, с индексами не очень удачное решение, нагляднее было бы, если бы это были соответствующие свойства с понятными именами

У меня сейчас вью тоже на индексах завязана. Пока не соображу, как лучше переписать код, чтобы избавиться от них. Тут мне нужно понять сначала, какие ошибки я допустила в целом в архитектуре MVC. Поправлю это, как разберусь с ишьюзом #13 Main View.

**Comment by MorganaLF** [comment]
> Я бы отнесла колбэки не к структуре вью, а к настройкам модели. То есть пользователь может в настройках, например, задать:
> 
> ```
> $('.slider').sliderPlugin({
>   min: 0,
>   max: 100,
>   callbacks: {
>     onThumbMouseDown: function() {
>       alert('mouse down!');
>     },
>   },
> });
> ```
> 
> Модель эту функцию записывает в makeOnThumbMouseDownCallback, а контроллер вызывает её при наступлении события thumbDownEvent, выпускаемого главным видом.
> 
> Если модель будет игнорировать эти пользовательские настройки колбэков, непонятно, каким образом, контроллер может узнать о них.

Но можно ведь и не хранить их нигде, а просто в плагине генерировать соответствующие события, а пользователь их будет слушать и сам добавлять обработчики, когда ему надо.

**Comment by imin314** [comment]
Поправила. Теперь схема с колбэками следующая:
в плагине генерятся соответствующие jQuery события в ответ на события контроллера. Пользователь подписывается на события jQuery, а модель. вид и контроллер ничего не знают о колбэках.

От индексов тоже избавилась. Теперь в модели есть два значения minValue и maxValue. Чтобы не путать с границами всего слайдера, последние переименовала в minBoundary и maxBoundary,
