### ISSUE TITLE
Приведение типов

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#15]
Приводить строку к числу при помощи `+` плохая практика, об этом есть в airbnb и по идее это правило должно быть включено в линтере: 

https://github.com/airbnb/javascript#coercion--numbers

Model.ts
![Снимок экрана в 2019-11-15 09-11-46](https://user-images.githubusercontent.com/38564412/68920924-f6c05280-0787-11ea-80f7-1e9fdf7b7f87.png)

**Comment by imin314** [comment]
Почти полностью переписала слайдер, поэтому не получилось указывать ссылки на ишьюзы. Поправила эту проблему глобально. Использовала Number(...).
