### ISSUE TITLE
control-box

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#16]
А для чего тебе могли на демо-странице понадобиться события мыши? По идее у тебя же там только инпуты, чекбоксы и селекты

![Снимок экрана от 2020-01-20 10-08-13](https://user-images.githubusercontent.com/38564412/72705578-e56f3a00-3b6c-11ea-9dd2-e05a27d9e3c2.png)

**Comment by MorganaLF** [comment]
А нельзя в этом блоке выделить какие-то вложенные блоки? Какой-то он уж очень большой получился

![Снимок экрана от 2020-01-20 14-50-50](https://user-images.githubusercontent.com/38564412/72724489-7c032180-3b94-11ea-8124-40dac6fe847d.png)

**Comment by imin314** [comment]
> А для чего тебе могли на демо-странице понадобиться события мыши? По идее у тебя же там только инпуты, чекбоксы и селекты

События мыши нужны только для демонстрации работы колбэков плагина (группа инпутов и чекбоксов под названием Callbacks).

**Comment by imin314** [comment]
> А нельзя в этом блоке выделить какие-то вложенные блоки? Какой-то он уж очень большой получился
Это я согласна, попробую как-нибудь перекомпоновать эту группу.

**Comment by imin314** [comment]
Разделила большой блок General на несколько.

**Comment by MorganaLF** [comment]
Я не совсем поняла, какие изменения были сделаны)
Я имела в этом большом БЭМ-блоке `control-box` выделить какие-то вложенные БЭМ-блоки. 
Например, то, что лежит в fieldset, можно сделать блоком - они ведь повторяются и переиспользуются. Возможно, еще какие-то блоки выделить

![Снимок экрана от 2020-01-25 13-28-59](https://user-images.githubusercontent.com/38564412/73119705-c3175b00-3f76-11ea-99fe-60e9f9eb24bb.png)

**Comment by imin314** [comment]
Забыла про бэм совсем с этим MVC)) сейчас поправила. Добавила блоки fieldset и labeled-input.
