### ISSUE TITLE
Тесты

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#17]
Нужно добавить в конфиг karma coverage, чтобы можно было посмотреть процент покрытия плагина тестами

**Comment by imin314** [comment]
Добавила karma-coverage, пришлось переместить все тесты в отдельную папку. Иначе не получалось исключить файлы тестов из отчета.

**Comment by MorganaLF** [comment]
Еще небольшое усовершенствование: по идее тут еще можно в консоль вывести процент покрытия. И еще нужно повысить процент покрытия, хотя бы процентов до 80

![Снимок экрана от 2020-01-30 22-29-25](https://user-images.githubusercontent.com/38564412/73483327-476f4100-43b0-11ea-98d8-df7ef378bbef.png)

**Comment by imin314** [comment]
Оказалось, что я неправильно настроила coverage для webpack, и покрытие было не таким низким (примерно 77% по категории Branches).
Добавила новых тестов, чтобы поднять результат по всем файлам. Вот как сейчас выглядит.
![Screenshot_2](https://user-images.githubusercontent.com/40715953/73571224-b035e680-44a0-11ea-8ed5-ad0c96b6082a.png)

**Comment by imin314** [comment]
Не совсем поняла принцип, по которым он ищет непокрытый код. Надеюсь, такой процент покрытия достаточен.

**Comment by MorganaLF** [comment]
Да, я так и подумала, что скорее всего неправильно настроено, потому что очень странно выделялись непокрытые куски кода)
Я так понимаю, что непокрытый код ищется с учетом того, выполняется ли в процессе тестов какая-либо часть программы или нет. 
Мне кажется, что сейчас хороший результат, но вообще для интереса можешь поэкспериментировать, чтобы понять, какие части твоего кода плохо тестируются и по каким причинам.
