### ISSUE TITLE
Линтер

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#18]
Сейчас в package.json нет скрипта для запуска линтера

![Снимок экрана от 2020-01-20 11-56-10](https://user-images.githubusercontent.com/38564412/72712357-eb204c00-3b7b-11ea-9026-755ff835a347.png)

**Comment by imin314** [comment]
Добавила скрипт для запуска линтера, правда после его запуска появляется ошибка:
_Failed at the SliderPlugin_project@1.0.0 lint script._
Не пойму, это из-за того что линтер нашел ошибки?

**Comment by imin314** [comment]
С линтером разобралась, исправила ошибки и сообщение исчезло.
