### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#19]
Мне кажется, у модели поле `withDescreteChange` надо как-то переименовать иначе, я пока из контроллера до модели не добралась, не поняла, что это значит)
Плюс, я думаю, если поле возвращает булево значение, то и метод лучше переименовать, чтобы он начинался с with.., is..., а не с get, так будет очевиднее

**Controller.ts**
![Снимок экрана от 2020-01-20 12-06-59](https://user-images.githubusercontent.com/38564412/72713285-d775e500-3b7d-11ea-9c6f-93760243fad8.png)

**Comment by MorganaLF** [comment]
Переменные, аргументы функций, методы, функции - все должно иметь ясные и понятные имена, вот здесь, например, совсем непонятно, что такое `x`

**EventDispatcher.ts**
![Снимок экрана от 2020-01-20 12-16-28](https://user-images.githubusercontent.com/38564412/72713902-e1e4ae80-3b7e-11ea-850b-dd3a26b283f7.png)

**Comment by imin314** [comment]
Поправила.
Имя опции сменила на withSmoothSlide. Вроде понятнее так.
Метод не стала править, т.к. его в другой правке надо будет вообще убрать.
