### ISSUE TITLE
Рефакторинг модели

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#20]
А нельзя, чтобы это как-то так работало?

![Снимок экрана от 2020-01-20 12-28-27](https://user-images.githubusercontent.com/38564412/72714843-7a2f6300-3b80-11ea-9bb9-4b48e8d89cc9.png)

Вообще сейчас не совсем понятно, для чего это дублирование, чем отличается `model.getOption('minValue')` от `model.getMinValue()`, например?

**Comment by MorganaLF** [comment]
Мне кажется, все эти валидации стоит вынести в отдельный метод, сейчас получается, что метод `updateOptions` выполняет разные задачи, к тому же теоретически это может понадобиться в другом месте

![Снимок экрана от 2020-01-20 12-36-38](https://user-images.githubusercontent.com/38564412/72715513-a5ff1880-3b81-11ea-87a7-baefe089970b.png)

**Comment by MorganaLF** [comment]
Такие проверки лучше выносить в переменные, так будет лучше читаться

![Снимок экрана от 2020-01-20 12-45-51](https://user-images.githubusercontent.com/38564412/72716180-dc896300-3b82-11ea-9e5b-c9c2db8a7d09.png)

**Comment by imin314** [comment]
> Вообще сейчас не совсем понятно, для чего это дублирование, чем отличается `model.getOption('minValue')` от `model.getMinValue()`, например?

Избавилась от дублирующих методов, оставила только getOption.

**Comment by imin314** [comment]
> Мне кажется, все эти валидации стоит вынести в отдельный метод, сейчас получается, что метод `updateOptions` выполняет разные задачи, к тому же теоретически это может понадобиться в другом месте

Разбила метод updateOptions на два приватных метода: 
1) validateOptions - для проверки свойств модели, ошибка в которых приводит к OptionError и не позволяет отрисовать слайдер,
2) normalizeOptions - для преобразования остальных свойств модели к нормальному виду (булевы свойства, интервалы для шкалы).

**Comment by imin314** [comment]
> Такие проверки лучше выносить в переменные, так будет лучше читаться

Поправила
