### ISSUE TITLE
Single Responsibility методов

### ISSUE THREAD

**Issue by MorganaLF** [imin314/SliderPlugin_project#21]
Каждый метод должен выполнять только одну задачу: пункт 4 https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/goodPractice.md

Сейчас у тебя в `MainView` есть метод, который называется `updateOptions`, но на самом деле он не только обновляет опции, но и делает что-то с DOM

![Снимок экрана от 2020-01-20 12-56-55](https://user-images.githubusercontent.com/38564412/72717039-5bcb6680-3b84-11ea-8b2a-4a79de78f075.png)

И устанавливает положение элементов:

![Снимок экрана от 2020-01-20 12-57-25](https://user-images.githubusercontent.com/38564412/72717084-6f76cd00-3b84-11ea-9928-11709d7f6eb9.png)

**Comment by imin314** [comment]
Поправила. Во всех вьюхах updateOptions() переименовала в update(), а в дочерних еще разбила на методы, выполняющие одну функцию.
